# Generated by Django 6.0.1 on 2026-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('thumbnail_mini', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
            ],
        ),
    ]
